### ISSUE TITLE
When the humbug_reports drone fails to write a report into the database, it starts losing all subsequent reports

### ISSUE THREAD

**Issue by zomglings** [bugout-dev/drones#4]
The report is getting correctly added to the failure queue, but all subsequent reports fail to be added to the database *and* fail to be added to the failure queue with this error message:
```
Jul 30 02:08:05 ip-17-29-3-64 droneshumbugreports[1460]: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "uc_journal_entry_tags_journal_entry_id_tag"
Jul 30 02:08:05 ip-17-29-3-64 droneshumbugreports[1460]: DETAIL:  Key (journal_entry_id, tag)=(<redacted>, <redacted>) already exists.
Jul 30 02:08:05 ip-17-29-3-64 droneshumbugreports[1460]: [SQL: INSERT INTO journal_entry_tags (id, journal_entry_id, tag) VALUES (%(id)s, %(journal_entry_id)s, %(tag)s)]
Jul 30 02:08:05 ip-17-29-3-64 droneshumbugreports[1460]: [parameters: {'id': UUID('80a44aa5-5a81-4380-b769-bae741d5bb24'), 'journal_entry_id': UUID('<redacted>'), 'tag': '<redacted>'}]
Jul 30 02:08:05 ip-17-29-3-64 droneshumbugreports[1460]: (Background on this error at: http://sqlalche.me/e/13/gkpj) (Background on this error at: http://sqlalche.me/e/13/7s2a)
```

**Comment by zomglings** [comment]
The first problem is that we are lacking a `db_session.rollback()` on the error condition: https://github.com/bugout-dev/drones/blob/c09297902e30f1751b83973c668d41f71df0f451/drones/humbug_reports.py#L133

**Comment by zomglings** [comment]
The second problem is that there is no transaction boundary spanning the queue pop and the database write.

**Comment by zomglings** [comment]
We need to understand where the SQLAlchemy error was being raised, because it isn't being raised in the try block linked above.

**Comment by zomglings** [comment]
I understand the second issue now. The problem is that `process_humbug_tasks_queue` splits the reading of reports from redis and writing of reports to postgres into two separate functions.

Between reading and writing, it attempts to do something with the database (`get_humbug_integrations`).

*That* is the database operation that is failing, and the except block in `process_humbug_tasks_queue` does not save failed reports to the failed reports queue. It just prints the error and exits.

This error handling needs to be improved!

**Comment by kompotkot** [comment]
Added rollback in PR https://github.com/bugout-dev/drones/pull/14
